name: Deployment

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/cache@v4
        id: yarn-cache
        with:
          path: ~/.npm
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-

      - name: Installing Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Installing NPM Packages
        run: yarn --frozen-lockfile

      - name: Deploy
        run: yarn deploy

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-executable
          path: dist/tcp-proxy.exe
          retention-days: 28
